services:
  postgres:
    image: 'postgres:latest'
    container_name: join2play_container
    environment:
      - 'POSTGRES_DB=join2play_db'
      - 'POSTGRES_PASSWORD=root_password'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
